backend:
  name: git-gateway
  branch: main

media_folder: "public/uploads" # Path to store uploaded files
public_folder: "/uploads"      # URL path for the files

media_library:
  name: default
  config:

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
