backend:
  name: github
  repo: POISED-GENTLEMEN/poised-growth-hub
  branch: main
  auth_type: implicit
  app_id: 0v23L19B0J4OJg4mlwHeo

local_backend: true

media_folder: "public/uploads"
public_folder: "/uploads"

media_library:
  name: uploadcare
  config:
    publicKey: ""

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/content/posts"
    create: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Slug", name: "slug", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "coverImage", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Tags", name: "tags", widget: "list", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
